enum HelmetTypes
{
	HELMSLOT_NONE = 0,
	HELMSLOT_GREY = 1,
	HELMSLOT_BLUE = 2,
	HELMSLOT_PURPLE = 3,
	HELMSLOT_GOLDEN = 4,
};
enum ArmorTypes
{
	ARMORSLOT_NONE = 0,
	ARMORSLOT_GREY = 1,
	ARMORSLOT_BLUE = 2,
	ARMORSLOT_PURPLE = 3,
	ARMORSLOT_GOLDEN = 4,
	ARMORSLOT_MYTHIC = 5
};